# Generated by Django 3.0.2 on 2020-01-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_market_price', models.DecimalField(decimal_places=2, max_digits=21)),
                ('gold_bill_price', models.DecimalField(decimal_places=2, max_digits=21)),
                ('gold_old_ornaments_price', models.DecimalField(decimal_places=2, max_digits=21)),
                ('gold_24_carat', models.DecimalField(decimal_places=2, max_digits=21)),
                ('gold_22_carat', models.DecimalField(decimal_places=2, max_digits=21)),
                ('gold_18_carat', models.DecimalField(decimal_places=2, max_digits=21)),
                ('silver_without_bill_price', models.DecimalField(decimal_places=2, max_digits=21)),
                ('silver_with_bill_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=21, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
