# Generated by Django 3.0.3 on 2020-10-02 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_weight',
            new_name='product_gross_weight',
        ),
        migrations.AddField(
            model_name='product',
            name='product_labour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_measurement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_net_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_other_charge_diamond',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_other_charge_pearl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_other_charge_rodium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_other_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_seller',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Only Letters, Numbers and Hyphen(-) Allowed', regex='^([A-Za-z0-9\\-\\ ]+)$'), django.core.validators.MinLengthValidator(limit_value=3), django.core.validators.MaxLengthValidator(limit_value=50)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_specification',
            field=models.CharField(choices=[('F', 'FeMale'), ('M', 'Male'), ('O', 'Other')], default='O', max_length=1),
            preserve_default=False,
        ),
    ]
