# Generated by Django 3.0.3 on 2020-02-07 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only Letters, Numbers and Hyphen(-) Allowed', regex='^([A-Za-z0-9\\-]+)$')]),
        ),
    ]
