# Generated by Django 3.0.3 on 2020-02-07 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200207_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only Letters, Numbers and Hyphen(-) Allowed', regex='^([A-Za-z0-9\\-\\ ]+)$')]),
        ),
    ]
