# Generated by Django 3.0.2 on 2020-01-25 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only Alphabets Allowed', regex='^[a-zA-Z]*$')])),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Only Alphabets Allowed', regex='^[a-zA-Z]*$')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only Alphabets Allowed', regex='^[a-zA-Z]*$')])),
                ('sex', models.CharField(choices=[('F', 'FeMale'), ('M', 'Male')], max_length=1)),
                ('job', models.CharField(blank=True, help_text='Onlye Alphabets Allowed', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Only Alphabets Allowed', regex='^[a-zA-Z]*$')])),
                ('mobile_one', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Only 10 Digit Mobile Number Allowed', regex='^[1-9]\\d{9}$')])),
                ('mobile_two', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Only 10 Digit Mobile Number Allowed', regex='^[1-9]\\d{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_one', models.CharField(blank=True, max_length=100, null=True)),
                ('address_two', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(help_text='Only Alphabets Allowed', max_length=50, validators=[django.core.validators.RegexValidator(message='Only Alphabets Allowed', regex='^[a-zA-Z]*$')])),
                ('pincode', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Six Digit PinCode', regex='^[1-9]\\d{5}$')])),
                ('country', models.CharField(choices=[('IND', 'India'), ('USA', 'United States of America'), ('CAN', 'Canada'), ('CHN', 'China'), ('ARE', 'United Arab Emirates')], default='IND', max_length=3)),
                ('detail', models.TextField(blank=True, help_text='Maximum 300 Characters Allowed', max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=300)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
