# Generated by Django 3.1.1 on 2020-09-19 12:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_product_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('sell_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
                ('sell_product_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sell.sellproductlist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sell',
            constraint=models.UniqueConstraint(fields=('person', 'sell_product_list'), name='person_sell_product'),
        ),
    ]
