# Generated by Django 3.0.3 on 2020-02-12 11:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_product_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('sell_product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='stock.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.Person')),
                ('sell_product_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sell.SellProductList')),
            ],
        ),
    ]
