# Generated by Django 3.0.3 on 2020-02-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproductlist',
            name='sell_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Stock'),
        ),
    ]
