# Generated by Django 3.0.3 on 2020-02-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20200212_1715'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sell',
            constraint=models.UniqueConstraint(fields=('person', 'sell_product_list'), name='person_sell_product'),
        ),
        migrations.AlterModelTable(
            name='sell',
            table='Sell',
        ),
    ]
