# Generated by Django 3.0.3 on 2020-02-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_auto_20200212_1753'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sell',
            table='sell',
        ),
    ]
